version: '3.8'

services:
  switch-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: switch-app
    restart: unless-stopped
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=2025
      - FRONTEND_URL=https://kijumbesmart.co.tz
      
      # Appwrite Configuration
      - APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1
      - APPWRITE_PROJECT_ID=68ac2652001ca468e987
      - APPWRITE_DATABASE_ID=68ac3f000002c33d8048
      - APPWRITE_API_KEY=standard_d1aac338e34f0674a53aa08d7bd5e0129984b8753341dea5a016f628614092f6b781008906aecb5fbc805088799b0aff46f108a35d77828ecef11e9b5b36ed0fc783a53f0bfafed81cf0a78ee78b21cc1c5151ac392cd678240bbb86b04db612737c050a1e35ceff6fbc4b4e4d05e67bc4948cf455394dc26ca972cba86fe498
      - APPWRITE_PROJECT_NAME=kijumbe
      
      # Collection IDs
      - COLLECTION_USERS=users
      - COLLECTION_GROUPS=groups
      - COLLECTION_MEMBERS=members
      - COLLECTION_TRANSACTIONS=transactions
      - COLLECTION_PAYMENTS=payments
      - COLLECTION_OVERDRAFTS=overdrafts
      - COLLECTION_WHATSAPP_MESSAGES=whatsapp_messages
      - COLLECTION_WALLETS=wallets
      - COLLECTION_WALLET_TRANSACTIONS=wallet_transactions
      - COLLECTION_WALLET_PAYMENTS=wallet_payments
      
      # Payment Gateway (Selcom)
      - SELCOM_BASE_URL=https://apigw.selcommobile.com/v1
      - SELCOM_API_KEY=TILL61099541-971371e3edeb4690b35dea06ca6b1e78
      - SELCOM_API_SECRET=77faf6-fa1b4c-443f8d-aa6f91-b37939-59
      - SELCOM_MERCHANT_ID=TILL61099541
      - BASE_URL=https://kijumbesmart.co.tz
      
      # XMPP Configuration
      - XMPP_SERVER=ws://localhost:5280/ws
      - XMPP_DOMAIN=localhost
      - EJABBERD_WS_URL=ws://localhost:5280/ws
      - EJABBERD_DOMAIN=localhost
      - EJABBERD_API_URL=http://localhost:5280/api
      
      # Janus WebRTC Configuration
      - USE_JANUS=false
      - JANUS_URL=wss://janus.conf.meetecho.com/ws
      - JANUS_JS_URL=https://janus.conf.meetecho.com/janus.js
    networks:
      - switch-network
      - nginx-proxy-network # This will be the shared network with your existing nginx-proxy

  switch-nginx:
    image: nginx:alpine
    container_name: switch-nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    environment:
      - VIRTUAL_HOST=kijumbesmart.co.tz,www.kijumbesmart.co.tz
      - LETSENCRYPT_HOST=kijumbesmart.co.tz,www.kijumbesmart.co.tz
      - VIRTUAL_PORT=2025
    depends_on:
      - switch-app
    networks:
      - switch-network
      - nginx-proxy-network

  ejabberd:
    image: ejabberd/ecs
    container_name: switch-ejabberd
    restart: unless-stopped
    volumes:
      - ./ejabberd/conf:/home/ejabberd/conf
      - ./ejabberd/database:/home/ejabberd/database
      - ./ejabberd/logs:/home/ejabberd/logs
    ports:
      - "5222:5222"  # XMPP client connections
      - "5280:5280"  # HTTP admin interface
      - "5269:5269"  # Server-to-server
    environment:
      - XMPP_DOMAIN=kijumbesmart.co.tz
      - EJABBERD_ADMIN=admin@kijumbesmart.co.tz
      - EJABBERD_ADMIN_PWD=your_secure_admin_password
    networks:
      - switch-network

  janus:
    image: canyan/janus-gateway:latest
    container_name: switch-janus
    restart: unless-stopped
    volumes:
      - ./janus/conf:/usr/local/etc/janus
    ports:
      - "8088:8088"  # REST API
      - "8188:8188"  # WebSocket API
      - "8989:8989"  # Admin/Monitor
    environment:
      - DOCKER_IP=kijumbesmart.co.tz
      - DOCKER_NETWORK=switch-network
    networks:
      - switch-network

networks:
  switch-network:
    name: switch-network
    driver: bridge
  nginx-proxy-network:
    external: true
    name: nginx-proxy-network # This should match your existing nginx-proxy network name
