version: '3.8'

# ============================================
# Networks Configuration
# ============================================
networks:
  switch-network:
    name: switch-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# ============================================
# Volumes Configuration
# ============================================
volumes:
  app-logs:
    driver: local
  app-uploads:
    driver: local
  ejabberd-conf:
    driver: local
  ejabberd-database:
    driver: local
  ejabberd-logs:
    driver: local
  janus-conf:
    driver: local
  nginx-ssl:
    driver: local

# ============================================
# Services Configuration
# ============================================
services:
  # Main Application Service
  switch-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: switch-app:latest
    container_name: switch-app
    restart: unless-stopped
    networks:
      switch-network:
        ipv4_address: 172.20.0.10
    ports:
      - "2025:2025"  # Main application port
    volumes:
      - app-logs:/app/logs
      - app-uploads:/app/uploads
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=2025
      - HOST=0.0.0.0
      - BASE_URL=https://kijumbesmart.co.tz
      - API_URL=https://kijumbesmart.co.tz/api
      
      # Appwrite Configuration
      - VITE_APPWRITE_ENDPOINT=${VITE_APPWRITE_ENDPOINT:-https://fra.cloud.appwrite.io/v1}
      - VITE_APPWRITE_PROJECT_ID=${VITE_APPWRITE_PROJECT_ID}
      - VITE_APPWRITE_DATABASE_ID=${VITE_APPWRITE_DATABASE_ID}
      - VITE_APPWRITE_API_KEY=${VITE_APPWRITE_API_KEY}
      
      # Collection IDs
      - VITE_COLLECTION_USERS=${VITE_COLLECTION_USERS:-users}
      - VITE_COLLECTION_GROUPS=${VITE_COLLECTION_GROUPS:-groups}
      - VITE_COLLECTION_MEMBERS=${VITE_COLLECTION_MEMBERS:-members}
      - VITE_COLLECTION_TRANSACTIONS=${VITE_COLLECTION_TRANSACTIONS:-transactions}
      - VITE_COLLECTION_PAYMENTS=${VITE_COLLECTION_PAYMENTS:-payments}
      - VITE_COLLECTION_OVERDRAFTS=${VITE_COLLECTION_OVERDRAFTS:-overdrafts}
      - VITE_COLLECTION_WHATSAPP_MESSAGES=${VITE_COLLECTION_WHATSAPP_MESSAGES:-whatsapp_messages}
      - VITE_COLLECTION_WALLETS=${VITE_COLLECTION_WALLETS:-wallets}
      - VITE_COLLECTION_WALLET_TRANSACTIONS=${VITE_COLLECTION_WALLET_TRANSACTIONS:-wallet_transactions}
      - VITE_COLLECTION_WALLET_PAYMENTS=${VITE_COLLECTION_WALLET_PAYMENTS:-wallet_payments}
      - VITE_COLLECTION_VIDEOS=${VITE_COLLECTION_VIDEOS:-videos}
      - VITE_COLLECTION_SHORTS=${VITE_COLLECTION_SHORTS:-shorts}
      - VITE_COLLECTION_LIVE_STREAMS=${VITE_COLLECTION_LIVE_STREAMS:-live_streams}
      - VITE_COLLECTION_STREAM_COMMENTS=${VITE_COLLECTION_STREAM_COMMENTS:-stream_comments}
      - VITE_COLLECTION_STATUS_UPDATES=${VITE_COLLECTION_STATUS_UPDATES:-status_updates}
      
      # Storage Buckets
      - VITE_BUCKET_VIDEOS=${VITE_BUCKET_VIDEOS:-videos}
      - VITE_BUCKET_THUMBNAILS=${VITE_BUCKET_THUMBNAILS:-thumbnails}
      - VITE_BUCKET_PROFILE_PICTURES=${VITE_BUCKET_PROFILE_PICTURES:-profile_pictures}
      - VITE_BUCKET_STATUS_MEDIA=${VITE_BUCKET_STATUS_MEDIA:-status_media}
      
      # CORS Configuration
      - CORS_ORIGIN=${CORS_ORIGIN:-https://kijumbesmart.co.tz}
      - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
      - CORS_ALLOWED_HEADERS=${CORS_ALLOWED_HEADERS:-Content-Type,Authorization,X-Requested-With}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      
      # Payment Gateway (Selcom)
      - VITE_SELCOM_BASE_URL=${VITE_SELCOM_BASE_URL:-https://apigw.selcommobile.com/v1}
      - VITE_SELCOM_API_KEY=${VITE_SELCOM_API_KEY}
      - VITE_SELCOM_API_SECRET=${VITE_SELCOM_API_SECRET}
      - VITE_SELCOM_MERCHANT_ID=${VITE_SELCOM_MERCHANT_ID}
      - VITE_BASE_URL=${VITE_BASE_URL:-https://kijumbesmart.co.tz}
      
      # XMPP Configuration
      - XMPP_DOMAIN=${XMPP_DOMAIN:-kijumbesmart.co.tz}
      - XMPP_SERVER=${XMPP_SERVER:-wss://kijumbesmart.co.tz/xmpp-ws}
      - VITE_XMPP_SERVER=${VITE_XMPP_SERVER:-wss://kijumbesmart.co.tz/xmpp-ws}
      - EJABBERD_API_URL=http://ejabberd:5280/api
      - EJABBERD_ADMIN=${EJABBERD_ADMIN:-admin@kijumbesmart.co.tz}
      - EJABBERD_ADMIN_PWD=${EJABBERD_ADMIN_PWD}
      
      # Janus WebRTC Configuration
      - USE_JANUS=${USE_JANUS:-true}
      - JANUS_WS_URL=${JANUS_WS_URL:-wss://kijumbesmart.co.tz/janus-ws}
      - VITE_JANUS_WS_URL=${VITE_JANUS_WS_URL:-wss://kijumbesmart.co.tz/janus-ws}
      - JANUS_HTTP_URL=${JANUS_HTTP_URL:-https://kijumbesmart.co.tz/janus}
      - JANUS_JS_URL=${JANUS_JS_URL:-https://kijumbesmart.co.tz/janus/janus.js}
      
      # Frontend URLs
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL:-https://kijumbesmart.co.tz}
      - VITE_API_URL=${VITE_API_URL:-https://kijumbesmart.co.tz/api}
    
    env_file:
      - .env
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2025/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    depends_on:
      ejabberd:
        condition: service_started
      janus:
        condition: service_started

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: switch-nginx
    restart: unless-stopped
    networks:
      switch-network:
        ipv4_address: 172.20.0.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - nginx-ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - DOMAIN=kijumbesmart.co.tz
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    depends_on:
      - switch-app

  # ejabberd XMPP Server
  ejabberd:
    image: ejabberd/ecs:latest
    container_name: switch-ejabberd
    restart: unless-stopped
    networks:
      switch-network:
        ipv4_address: 172.20.0.20
    volumes:
      - ejabberd-conf:/home/ejabberd/conf
      - ejabberd-database:/home/ejabberd/database
      - ejabberd-logs:/home/ejabberd/logs
    ports:
      - "5222:5222"  # XMPP client connections
      - "5280:5280"  # HTTP admin interface
      - "5269:5269"  # Server-to-server
    environment:
      - XMPP_DOMAIN=${XMPP_DOMAIN:-kijumbesmart.co.tz}
      - EJABBERD_ADMIN=${EJABBERD_ADMIN:-admin@kijumbesmart.co.tz}
      - EJABBERD_ADMIN_PWD=${EJABBERD_ADMIN_PWD:-change_this_secure_password}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

  # Janus WebRTC Gateway
  janus:
    image: canyan/janus-gateway:latest
    container_name: switch-janus
    restart: unless-stopped
    networks:
      switch-network:
        ipv4_address: 172.20.0.30
    volumes:
      - janus-conf:/usr/local/etc/janus
    ports:
      - "8088:8088"  # REST API
      - "8188:8188"  # WebSocket API
      - "8989:8989"  # Admin/Monitor
      - "10000-10200:10000-10200/udp"  # RTP/RTCP ports
    environment:
      - DOCKER_IP=${DOCKER_IP:-kijumbesmart.co.tz}
      - DOCKER_NETWORK=switch-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
