version: '3.8'

# Use a project-specific name prefix to avoid conflicts
name: switch

networks:
  switch-network:
    name: switch-network
    driver: bridge
  nginx-proxy-network:
    name: nginx-proxy-network
    external: true

services:
  switch-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: switch-app
    restart: unless-stopped
    networks:
      - switch-network
      - nginx-proxy-network
    ports:
      - "2025:2025"
      - "2026:2026"  # For XMPP if needed
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=2025
      - HOST=0.0.0.0
      - FRONTEND_URL=https://93.127.203.151:2025
      - VITE_BASE_URL=https://93.127.203.151:2025
      
      # XMPP Configuration
      - XMPP_SERVER=wss://93.127.203.151:2026/ws
      - XMPP_DOMAIN=93.127.203.151:2025
      - EJABBERD_WS_URL=wss://93.127.203.151:2026/ws
      - EJABBERD_DOMAIN=93.127.203.151:2025
      - EJABBERD_API_URL=https://93.127.203.151:2026/api
      
      # Appwrite Configuration
      - VITE_APPWRITE_ENDPOINT=https://fra.cloud.appwrite.io/v1
      - VITE_APPWRITE_PROJECT_ID=68ac2652001ca468e987
      - VITE_APPWRITE_DATABASE_ID=68ac3f000002c33d8048
      - VITE_APPWRITE_API_KEY=${VITE_APPWRITE_API_KEY}
      
      # Collection IDs
      - VITE_COLLECTION_USERS=users
      - VITE_COLLECTION_GROUPS=groups
      - VITE_COLLECTION_MEMBERS=members
      - VITE_COLLECTION_TRANSACTIONS=transactions
      - VITE_COLLECTION_PAYMENTS=payments
      - VITE_COLLECTION_OVERDRAFTS=overdrafts
      - VITE_COLLECTION_WHATSAPP_MESSAGES=whatsapp_messages
      - VITE_COLLECTION_WALLETS=wallets
      - VITE_COLLECTION_WALLET_TRANSACTIONS=wallet_transactions
      - VITE_COLLECTION_WALLET_PAYMENTS=wallet_payments
      
      # CORS Configuration
      - CORS_ORIGIN=https://93.127.203.151:2025
      - CORS_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=Content-Type,Authorization,X-Requested-With
      - CORS_CREDENTIALS=true
      
      # Payment Gateway (Selcom)
      - VITE_SELCOM_BASE_URL=https://apigw.selcommobile.com/v1
      - VITE_SELCOM_API_KEY=${VITE_SELCOM_API_KEY}
      - VITE_SELCOM_API_SECRET=${VITE_SELCOM_API_SECRET}
      - VITE_SELCOM_MERCHANT_ID=${VITE_SELCOM_MERCHANT_ID}
      - VITE_BASE_URL=https://93.127.203.151:2025
      
      # XMPP/Janus Configuration
      - XMPP_SERVER=wss://93.127.203.151:2025:2026/ws
      - XMPP_DOMAIN=93.127.203.151:2025
      - EJABBERD_WS_URL=wss://93.127.203.151:2025:2026/ws
      - EJABBERD_DOMAIN=93.127.203.151:2025
      - EJABBERD_API_URL=https://93.127.203.151:2025:2026/api
      - USE_JANUS=true
      - JANUS_URL=wss://93.127.203.151:2025:8188
      - JANUS_JS_URL=https://93.127.203.151:2025:8088/janus.js
    
    env_file:
      - .env
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2025/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: switch-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - switch-network
      - nginx-proxy-network
    depends_on:
      - switch-app

  ejabberd:
    image: ejabberd/ecs
    container_name: switch-ejabberd
    restart: unless-stopped
    volumes:
      - ./ejabberd/conf:/home/ejabberd/conf
      - ./ejabberd/database:/home/ejabberd/database
      - ./ejabberd/logs:/home/ejabberd/logs
    ports:
      - "5222:5222"  # XMPP client connections
      - "2026:2026"  # HTTP admin interface
      - "5269:5269"  # Server-to-server
    environment:
      - XMPP_DOMAIN=93.127.203.151:2025
      - EJABBERD_ADMIN=admin@93.127.203.151:2025
      - EJABBERD_ADMIN_PWD=your_secure_admin_password
    networks:
      - switch-network

  janus:
    image: canyan/janus-gateway:latest
    container_name: switch-janus
    restart: unless-stopped
    volumes:
      - ./janus/conf:/usr/local/etc/janus
    ports:
      - "8088:8088"  # REST API
      - "8188:8188"  # WebSocket API
      - "8989:8989"  # Admin/Monitor
    environment:
      - DOCKER_IP=93.127.203.151:2025
      - DOCKER_NETWORK=switch-network
    networks:
      - switch-network
