#!/bin/bash

# Update .env with Appwrite collection and bucket IDs

cd /root/Switch

# Backup current .env
cp .env .env.backup.$(date +%Y%m%d_%H%M%S)

# Add collection IDs
cat >> .env << 'EOF'

# Appwrite Collection IDs
VITE_APPWRITE_COLLECTION_USERS=users
VITE_APPWRITE_COLLECTION_WALLETS=wallets
VITE_APPWRITE_COLLECTION_TRANSACTIONS=wallet_transactions
VITE_APPWRITE_COLLECTION_GROUPS=groups
VITE_APPWRITE_COLLECTION_MESSAGES=messages
VITE_APPWRITE_COLLECTION_CALLS=calls
VITE_APPWRITE_COLLECTION_VIDEOS=videos
VITE_APPWRITE_COLLECTION_SHORTS=shorts
VITE_APPWRITE_COLLECTION_LIVE_STREAMS=live_streams
VITE_APPWRITE_COLLECTION_STATUS_UPDATES=status_updates
VITE_APPWRITE_COLLECTION_PAYMENTS=payments
VITE_APPWRITE_COLLECTION_OVERDRAFTS=overdrafts
VITE_APPWRITE_COLLECTION_WALLET_PAYMENTS=wallet_payments
VITE_APPWRITE_COLLECTION_WHATSAPP_MESSAGES=whatsapp_messages

# Appwrite Bucket IDs
VITE_APPWRITE_BUCKET_AVATARS=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_MEDIA=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_DOCUMENTS=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_VIDEOS=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_THUMBNAILS=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_PROFILE_PICTURES=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_STATUS_MEDIA=68d413170005fcbe55d2
VITE_APPWRITE_BUCKET_STREAMS=68d413170005fcbe55d2
EOF

echo "✓ Environment variables updated!"
echo "✓ Backup saved"
echo ""
echo "Restarting switch-app container..."
docker compose restart switch-app

echo ""
echo "Checking logs..."
sleep 3
docker logs switch-app --tail 20
